### ISSUE TITLE
Establish Voting Members

### ISSUE THREAD

**Issue by johnclary** [openmobilityfoundation/privacy-committee#1]

**Comment by jfh01** [comment]
At the 2020-01-15 OMF Board Meeting the following people were appointed as initial voting members for this committee:

* Alex Demisch -  San Francisco Municipal Transportation Agency
* John Clary  -  City of Austin (co-chair)
* Steve Hoyt-McBeth - Portland Bureau of Transportation
* Josh Johnson - City of Minneapolis
* Matt Worona - City of Kelowna
* Michael Schnuerle - Louisville Metro Government
* Irina Slavina - Blue Systems USA
* Marla Westervelt - Bird (co-chair)
* Maggie Mobley - Lacuna

Future voting members may be added by the board at a later date.
