### ISSUE TITLE
Updates to State of the Practice Wiki

### ISSUE THREAD

**Issue by johnclary** [openmobilityfoundation/privacy-committee#17]
Working from [this branch](https://github.com/openmobilityfoundation/privacy-committee/tree/jc-state-of-practice-v1.2).

- SAE Mobility Data Collaborative: *Data Sharing Glossary and Metrics for Shared Micromobility* and *Data Sharing Glossary and Metrics for Shared Micromobility* are available to download [here](https://mdc.sae-itc.com/#work)

- Shared-Use Mobility Center: [Objective-Driven Data Sharing for Transit Agencies in Mobility Partnerships](https://learn.sharedusemobilitycenter.org/overview/white-paper-objective-driven-data-sharing-for-transit-agencies-in-mobility-partnerships/)

- Populus's white paper (there website is down atm)

**Comment by johnclary** [comment]
Data Aggregation methods:

From @ FPF

o A Visual Guide to Practical Data De-Identification - https://fpf.org/2016/04/25/a-visual-guide-to-practical-data-de-identification/
o NIST, De-Identification of Personal Data - http://nvlpubs.nist.gov/nistpubs/ir/2015/NIST.IR.8053.pdf
• NIST, De-Identifying Government Datasets - http://csrc.nist.gov/publications/drafts/800-188/sp800_188_draft.pdf
o Federal Committee on Statistical Methodology, Report on Statistical Disclosure Limitation Methodology Working Paper No. 22, https://www.hhs.gov/sites/default/files/spwp22.pdf ((soon to be updated as part of the Federal Data Strategy – forthcoming summer 2020))
• For EU-inclined folks: Article 29 WP Opinion on Anonymisation Techniques - https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2014/wp216_en.pdf
• UK Anon, Anonymisation Decision-Making Framework - http://ukanon.net/wp-content/uploads/2015/05/The-Anonymisation-Decision-making-Framework.pdf
• On emerging techniques: https://royalsociety.org/-/media/policy/projects/privacy-enhancing-technologies/privacy-enhancing-technologies-report.pdf

And specifically on open data:
* DataSF, Open Data Release Toolkit, https://drive.google.com/file/d/0B0jc1tmJAlTcR0RMV01PM2NyNDA/view
• Harvard Berkman Klein Center for Internet and Society, Open Data Privacy Playbook, https://cyber.harvard.edu/publications/2017/02/opendataprivacyplaybook
• FPF’s Seattle/Open Data Privacy Risk Assessment - https://fpf.org/wp-content/uploads/2018/01/FPF-Open-Data-Risk-Assessment-for-City-of-Seattle.pdf (especially Appendix C/the chart starting on pg. 43)

**Comment by johnclary** [comment]
From SANDAG:

SANDAG in the process of examining these resources:

Song, Dahlmeier, & Bressan, Not so unique in the crowd: A simple and effective algorithm for anonymizing location data (2014), http://ceur-ws.org/Vol-1225/pir2014_submission_11.pdf

Lily Hay Newman, Google Wants to Help Tech Companies Know Less About You (Sept. 5, 2019), https://www.wired.com/story/google-differential-privacy-open-source/ (describing the open-source differential privacy tools made available at https://github.com/google/differential-privacy/tree/master/differential_privacy).

**Comment by johnclary** [comment]
Seattle's mobility data privacy and sharing guidelines: https://www.seattle.gov/Documents/Departments/SDOT/NewMobilityProgram/Mobility_Data_Guidelines_01142020.pdf

**Comment by johnclary** [comment]
Reminder to include sample data sharing agreements as well.

**Comment by jfh01** [comment]
Would ask that we separate mobility-specific resources for more general ones.
