### ISSUE TITLE
Add voting members to the README

### ISSUE THREAD

**Issue by jfh01** [openmobilityfoundation/privacy-committee#21]
We should list the voting members of the committee (and its chairs) on the main README page. Approved list is here:

https://drive.google.com/drive/folders/1Pl3o5yDPEfyDg0tFpJE9uvPapIPi4YlH

**Comment by schnuerle** [comment]
I can just put that on there for now, then you all can edit it.

**Comment by schnuerle** [comment]
Created PR #22 for your review.

**Comment by schnuerle** [comment]
Added.
