### ISSUE TITLE
Add LA's Use and Retention ordinance to State of Practice

### ISSUE THREAD

**Issue by johnclary** [openmobilityfoundation/privacy-committee#26]
Add LA's [Use and Retention ordinance](http://clkrep.lacity.org/onlinedocs/2019/19-1355_rpt_DOT_6-14-2020.pdf)

**Comment by schnuerle** [comment]
Updated [here](https://github.com/openmobilityfoundation/privacy-committee/commit/fff4e58111fc6b9a5b4d60b8a6524da34393333e#diff-1bb5f30915ff44e8e0259f0df01d5709) and ready to close this issue.
