### ISSUE TITLE
Consider adding ViaNova GDPR materials to State of Practice

### ISSUE THREAD

**Issue by jfh01** [openmobilityfoundation/privacy-committee#30]
The company ViaNova has shared two resources related to GDPR and MDS. We should consider linking them in our state of practice.

- The [GDPR statement](https://f.hubspotusercontent30.net/hubfs/6456989/Vianova_GDPR-Statement.pdf) provides information on how GDPR applies to MDS data and how the parties involved can be compliant
- The [Polis Network Presentation](https://f.hubspotusercontent30.net/hubfs/6456989/Vianova_Polis-Working-Group_2020.pdf) is saying the same but under a presentation format.

**Comment by schnuerle** [comment]
Maybe this can go in a new "Consumer Rights" section under "Privacy Principles, Policies, and Guidelines", and can link to these examples for now, with more being added around GDPR, CalECPA, etc as they become available. 

Vianova also has this blog post about [GDPR and MDS](https://medium.com/vianova/practical-guide-to-mobility-data-sharing-personal-privacy-under-gdpr-ruling-1ea73950c21d), though I think the statement is more detailed and clear.

**Comment by johnclary** [comment]
@schnuerle i like that suggestion. will open a PR but won't merge just yet.

**Comment by johnclary** [comment]
Here's [the PR](https://github.com/openmobilityfoundation/privacy-committee/pull/31).

@jfh01 @schnuerle the presentation has good content but is fairly broad. I think we should reference it in a different section, if at all. Thoughts?

**Comment by schnuerle** [comment]
I think referencing certain sections (pages 19-28) after the link to the presentation would be helpful.  It's some of the content from the statement, but presented in a a more visual and readable way with some more details.

**Comment by jfh01** [comment]
Yeah, I agree that the presentation format is more accessible than the statement. I like the suggestion of referencing specific pages from the state of practice.

**Comment by johnclary** [comment]
Done and merging. Thanks.
